if(EXISTS "D:/NumeroNexus/ChaosNexus/build-release/tests/unit/kernel/nexus-kernel-tests[1]_tests.cmake")
  include("D:/NumeroNexus/ChaosNexus/build-release/tests/unit/kernel/nexus-kernel-tests[1]_tests.cmake")
else()
  add_test(nexus-kernel-tests_NOT_BUILT nexus-kernel-tests_NOT_BUILT)
endif()
