if(EXISTS "D:/NumeroNexus/ChaosNexus/build-release/tests/unit/types/nexus-types-tests[1]_tests.cmake")
  include("D:/NumeroNexus/ChaosNexus/build-release/tests/unit/types/nexus-types-tests[1]_tests.cmake")
else()
  add_test(nexus-types-tests_NOT_BUILT nexus-types-tests_NOT_BUILT)
endif()
