if(EXISTS "D:/NumeroNexus/ChaosNexus/build-release/tests/unit/scheduler/nexus-scheduler-tests[1]_tests.cmake")
  include("D:/NumeroNexus/ChaosNexus/build-release/tests/unit/scheduler/nexus-scheduler-tests[1]_tests.cmake")
else()
  add_test(nexus-scheduler-tests_NOT_BUILT nexus-scheduler-tests_NOT_BUILT)
endif()
